apiVersion: argoproj.io/v1alpha1
kind: Workflow                  # new type of k8s spec
metadata:
  generateName: sidecar-nginx-    # name of the workflow spec
spec:
  entrypoint: sidecar-nginx-example          # invoke the whalesay template
  templates:
  - name: sidecar-nginx-example              # name of the template
    container:
      image: geoincaks/curl
      command: [sh,c]         # the command we're executing
      args: ["until `curl -G 'http://127.0.0.1/' >& /tmp/out`; do echo sleep 1; done && cat /tmp/out"]
      resources:                # limit the resources
        limits:
          memory: 32Mi
          cpu: 100m
    sidecars:
    - name: nginx
      image: nginx:1.13