apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: build-node-js-repo-
spec:
  entrypoint: git-clone
  templates:
  - name: git-clone
    inputs:
      artifacts:
      - name: argo-source
        path: /src
        git:
          repo: https://github.com/kintohub/node-examples.git
          revision: "master"
    container:
      image: node:8.9-alpine
      command: [sh, -c]
      args: ["npm install"]
      workingDir: /src