apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: a02-coinflip-
spec:
  entrypoint: a02
  templates:
  - name: a02
    steps:
    - - name: step01
        template: step01
    - - name: heads
        template: heads
        when: "{{steps.step01.outputs.result}} == heads"
      - name: tails
        template: tails
        when: "{{steps.step01.outputs.result}} == tails"
  - name: step01
    script:
      image: python:alpine3.6
      command: [python]
      source: |
        import random
        result= "heads" if random.randint(0,1) else "tails"
        print(result)
  - name: heads
    container: 
      image: alpine:3.6
      command: [sh, -c]
      args: ["echo \"It waas heads\""]
  - name: tails
    container: 
      image: alpine:3.6
      command: [sh, -c]
      args: ["echo \"It waas tails\""]    