apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: a03-loops-
spec:
  entrypoint: loops
  templates:
  - name: loops
    steps:
    - - name: print-message
        template: whalesay
        arguments:
          parameters:
          - name: message
            value: "{{item}}"
            
        withItems:
        - hello
        - bye
  
  - name: whalesay
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]
