apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: a04-diamond-
spec:
  entrypoint: diamond
  templates:
  - name: diamond
    dag:
      tasks:
      - name: A
        template: echo
        arguments:
          parameters: [{name: message, value: A}]
      - name: B
        dependencies: [A]
        template: echo
        arguments:
          parameters: [{name: message, value: B}]      
      - name: C
        dependencies: [A]
        template: echo
        arguments:
          parameters: [{name: message, value: C}] 
      - name: D
        dependencies: [B,C]
        template: echo
        arguments:
          parameters: [{name: message, value: D}] 
  - name: echo
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]