# This example demonstrates how to reference kubernetes secrets in a workflow.
# Secrets should be stored externally from the workflow as kubernetes secrets,
# and accessed using normal kubernetes facilities, such as volume mounting the
# secret, or as an environment variable. This example shows both approaches.
# For more details, see kubernetes documentation on secrets:
# https://kubernetes.io/docs/concepts/configuration/secret/
#
# To run this example, first create the secret by running:
# kubectl create secret generic my-secret --from-literal=mypassword=S00perS3cretPa55word
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: art01-secrets-
spec:
  entrypoint: print-secret
  # To use a secret as files, it is exactly the same as mounting secrets as in
  # a pod spec. First add an volume entry in the spec.volumes[]. Name the volume
  # anything. spec.volumes[].secret.secretName should match the name of the k8s
  # secret, which was created using kubectl. In any container template spec, add
  # a mount to volumeMounts referencing the volume name and a mount path.
  volumes:
  - name: my-secret-vol
    secret:
      secretName: argo-artifacts
  templates:
  - name: print-secret
    container:
      image: geoincaks/whalesay:0.1.1
      command: [sh, -c]
      args: [        "cowsay -f tux statis A  $MYSECRETPASSWORD "      ]
      # To use a secret as an environment variable, use the valueFrom with a
      # secretKeyRef. valueFrom.secretKeyRef.name should match the name of the
      # k8s secret, which was created using kubectl. valueFrom.secretKeyRef.key
      # is the key you want to use as the value of the environment variable.

        # echo "secret from env: $MYSECRETPASSWORD";
        # echo "secret from file: `cat /secret/mountpath/accesskey`";
      # echo "secret from file: `cat /secret/mountpath/mypassword`
      env:
      - name: MYSECRETPASSWORD
        valueFrom:
          secretKeyRef:
            name: argo-artifacts
            key: accesskey
      volumeMounts:
      - name: my-secret-vol
        mountPath: "/secret/mountpath"