apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
  - name: payload
    eventSourceName: webhook
    eventName: devops-toolkit
  triggers:
  - template:
      name: payload
      k8s:
        group: ""
        version: v1
        resource: pods
        operation: create
        source:
          resource:
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow                  # new type of k8s spec
            metadata:
              generateName: hello-world-    # name of the workflow spec
            spec:
              entrypoint: whalesay          # invoke the whalesay template
              templates:
              - name: whalesay              # name of the template
                container:
                  image: docker/whalesay
                  command: [cowsay]
                  args: ["This is the message you sent me:\n", ""]
                  resources:                # limit the resources
                    limits:
                      memory: 32Mi
                      cpu: 100m
        parameters:
          - src:
              dependencyName: payload
              dataKey: body.message
            dest: spec.containers.0.args.1
