apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook
spec:
  service:
    ports:
      - port: 15000
        targetPort: 15000
  webhook:
    devops-toolkit:
      port: "15000"
      endpoint: /devops-toolkit
      method: POST
