apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook
spec:
  service:
    ports:
      - port: 16000
        targetPort: 16000
  webhook:
    example:
      port: "16000"
      endpoint: /example
      method: POST