apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook40
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
    - name: test-dep
      eventSourceName: webhook
      eventName: example4
  triggers:
    - template:
        name: webhook-workflow-trigger
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: coinflip4-
              spec:
                entrypoint: coinflip
                templates:
                - name: coinflip
                  steps:
                  - - name: flip-coin
                      template: flip-coin
                  - - name: heads
                      template: heads
                      when: "{{steps.flip-coin.outputs.result}} == heads"
                    - name: tails
                      template: tails
                      when: "{{steps.flip-coin.outputs.result}} == tails"

                - name: flip-coin
                  script:
                    image: python:alpine3.6
                    command: [python]
                    source: |
                      import random
                      result = "heads" if random.randint(0,1) == 0 else "tails"
                      print(result)
                - name: heads
                  container:
                    image: alpine:3.6
                    command: [sh, -c]
                    args: ["echo \"it was heads\""]

                - name: tails
                  container:
                    image: alpine:3.6
                    command: [sh, -c]
                    args: ["echo \"it was tails\""]


          parameters:
            - src:
                dependencyName: test-dep
                dataKey: body.message
              dest: spec.containers.0.args.1