apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook02
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
    - name: test-dep
      eventSourceName: webhook
      eventName: example2
  triggers:
    - template:
        name: slack-trigger
        slack:
          channel: tfm
          message: hello world
          slackToken:
            key: token
            name: slack-secret
      parameters:
        - src:
            dependencyName: test-dep
            dataKey: body.channel
          dest: slack.channel
        - src:
            dependencyName: test-dep
            dataKey: body.message
          dest: slack.message