apiVersion: v1
kind: Pod
metadata:
  name: pytest
  labels:
    app: pytest
spec:
  containers:
  - name: pytest
    image: geoincaks/pythonimg:0.1.2
    command: ["/bin/sleep", "3650d"]
    imagePullPolicy: IfNotPresent
  restartPolicy: Always