apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: minio-input
spec:
  minio:
    example:
      bucket:
        name: input
      endpoint: argo-artifacts.argo:9000
      events:
        - s3:ObjectCreated:Put
      #  - s3:ObjectRemoved:Delete
      # type of the connection
      insecure: true
      accessKey:
        # Key within the K8s secret whose corresponding value (must be base64 encoded) is access key
        key: accesskey
        # Name of the K8s secret that contains the access key
        name: argo-artifacts
      # secretKey contains information about K8s secret that stores the secret key
      secretKey:
        # Key within the K8s secret whose corresponding value (must be base64 encoded) is secret key
        key: secretkey
        # Name of the K8s secret that contains the secret key
        name: argo-artifacts

#    example-with-filter:
#      bucket:
#        name: mybucket
#      endpoint: minio-service.argo-events:9000
#      events:
#        - s3:ObjectCreated:Put
#      # Filters to apply on the key
#      # Optional
#      # e.g. filter for key that starts with "hello-" and ends with ".txt"
#      filter:
#        prefix: "hello-"
#        suffix: ".txt"
#      insecure: true
#      accessKey:
#        key: accesskey
#        name: artifacts-minio
#      secretKey:
#        key: secretkey
#        name: artifacts-minio
