apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: miniotfm
spec:
  minio:
    exampleput:
      bucket:
        name: input
      endpoint: argo-artifacts.argo:9000
      events:
        - s3:ObjectCreated:Put
      #  - s3:ObjectRemoved:Delete
      insecure: true
      accessKey:
        key: accesskey
        name: argo-artifacts
      secretKey:
        key: secretkey
        name: argo-artifacts
    