apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: minio
spec:
  minio:
    example:
      bucket:
        name: infolder
      endpoint: argo-artifacts.argo:9000
      events:
        - s3:ObjectCreated:PutLegalHold
      #  - s3:ObjectCreated:PutRetention
      #  - s3:ObjectCreated:CompleteMultipartUpload
      #  - s3:ObjectCreated:Put
      #  - s3:ObjectRemoved:Delete
      insecure: true
      accessKey:
        key: accesskey
        name: argo-artifacts
      secretKey:
        key: secretkey
        name: argo-artifacts