apiVersion: v1
kind: Secret
metadata:
  name: tfm-secret
data:
  tokenkey: eG94Yi0xODA5NTQxNjA2NjI5LTE4Mjc3NjU2ODc0NTctT0RTTEhGV3lrRmlvbmVjVHVNYllOZlho
  signingSecret: YWE5YTExY2ZiMWEyYjNmMWVhYzEzMWZkYTQ0NzkzNWY=
  slackpost: aHR0cHM6Ly9zbGFjay5jb20vYXBpL2NoYXQucG9zdE1lc3NhZ2U=
  minioendpoint: aHR0cDovL2FyZ28tYXJ0aWZhY3RzLmFyZ286OTAwMA==
  bucketin: aW5mb2xkZXI=
  bucketout: b3V0Zm9sZGVy
  
# echo -n "YOUR-BASE64-ENCODED-OAUTH-TOKEN" | base64
# YOUR-BASE64-ENCODED-OAUTH-TOKEN