apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
    - name: test-dep
      eventSourceName: webhook
      eventName: devops-toolkit
  triggers:
    - template:
        name: workflow-trigger
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            s3:
              bucket:
                name: workflows
                key: hello-world.yaml
              endpoint: argo-artifacts.argo.svc.cluster.local:9000
              insecure: true
              accessKey:
                key: accesskey
                name: argo-artifacts
              secretKey:
                key: secretkey
                name: argo-artifacts
