apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  webhook:
    # event-source can run multiple HTTP servers. Simply define a unique port to start a new HTTP server
    example:
      port: "12000"
      endpoint: /example
      method: POST

    example2:
      port: "12000"
      endpoint: /example2
      method: POST

    example3:
      port: "12000"
      endpoint: /example3
      method: POST

    example4:
      port: "12000"
      endpoint: /example4
      method: POST      
# #Uncomment to use secure webhook
#    example-secure:
#      port: "13000"
#      endpoint: "/secure"
#      method: "POST"
